### ISSUE TITLE
reference for learning code

### ISSUE THREAD

**Issue by guo-zixuan** [sportdeath/range_mi#1]
Can you provide references for me to learn MI in robot exploration? @sportdeath

**Comment by sportdeath** [comment]
The paper I wrote this code for is a good start: https://www.rle.mit.edu/eems/wp-content/uploads/2020/03/2020_icra_fcmi.pdf

My thesis has more detail but it's not as clear or concise: https://dspace.mit.edu/handle/1721.1/124248
